version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./tools/postgres/data/pgdata:/var/lib/postgresql/data/pgdata"
      - "./tools/postgres/scripts:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_USER=blabla
      - POSTGRES_PASSWORD=blabla
      - POSTGRES_DB=blabla
      - PGDATA=/var/lib/postgresql/data/pgdata

  localstack:
    container_name: localstack
    command: /bin/bash /docker-entrypoint-initaws.d/sqs-queue.sh
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./tools/localstack/data:/var/lib/localstack/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./tools/localstack/initaws:/docker-entrypoint-initaws.d"
    
  victoriametrics:
    image: victoriametrics/victoria-metrics
    container_name: victoriametrics
    ports:
      - "8428:8428"
    command:
      - "--retentionPeriod=1"
    volumes:
      - victoriametrics-data:/victoria-metrics-data

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./tools/prometheus/prometheus.yml:/var/lib/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
volumes:
  victoriametrics-data:
  grafana-data: