openapi: 3.0.3
info:
  title: Jukebox API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Gets a pong
      operationId: Ping
      responses:
        '200':
          description: Pong string
          content:
            application/json:              
              schema:
                type: string
                format: simple
  /tracks:
    get:
      summary: Gets the registred songs
      operationId: GetTracks
      responses:
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseOgen"
        '200':
          description: Get tracks success
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Track"

    post:
      summary: Add a new track
      operationId: PostTracks
      requestBody: 
        $ref: "#/components/requestBodies/TrackInput"
      responses:
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseOgen"
        '200':
          description: OK
        '201':
          description: Created
  /tracks/{id}:
    parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Track Ulid ID
    delete:
      summary: Delete track with specific ID
      operationId: DeleteTrack
      responses:
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseOgen"
        '204': 
          description: No Content
    patch:
      summary: Update track with specific ID
      operationId: UpdateTrack
      requestBody: 
        $ref: "#/components/requestBodies/TrackInput"
      responses:
        '204': 
          description: No Content
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseOgen"
            
components:
  schemas:
    Track:
      description: Track response object
      type: object
      required: 
        - artist
        - title
        - duration
        - id
      properties:
        id:
          type: string
        title: 
          type: string
        artist:
          type: string
        duration:
          type: integer
        album:
          type: string
        genre:
          type: string

    ErrorResponseOgen:
      description: The default error response object generated by ogen
      type: object
      required:
        - error_message
        - status_code
      properties:
        error_message:
          type: string
        status_code:
          type: integer

  requestBodies:
    TrackInput:
      description: A JSON object containing the new track information
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - artist
              - title
              - duration
            properties:
              title: 
                type: string
              artist:
                type: string
              duration:
                type: integer
              album:
                type: string
              genre:
                type: string
