openapi: 3.0.3
info:
  title: Jukebox API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Gets a pong
      operationId: Ping
      responses:
        '200':
          description: Pong string
          content:
            application/json:              
              schema:
                type: string
                format: simple
