openapi: 3.0.3
info:
  title: Jukebox API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Gets a pong
      operationId: Ping
      responses:
        '200':
          description: Pong string
          content:
            application/json:              
              schema:
                type: string
                format: simple
  /tracks:
    get:
      summary: Gets the registred songs
      operationId: GetTracks
      responses:
        '200':
          description: Get tracks success
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Track"
    post:
      summary: Add a new track
      operationId: PostTracks
      requestBody: 
        $ref: "#/components/requestBodies/TrackInput"
      responses:
        '200':
          description: OK
        '201':
          description: Created

components:
  schemas:
    Track:
      description: Track response object
      type: object
      required: 
        - artist
        - title
        - duration
      properties:
        title: 
          type: string
        artist:
          type: string
        duration:
          type: integer
        album:
          type: string
        genre:
          type: string
  requestBodies:
    TrackInput:
      description: A JSON object containing the new track information
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - artist
              - title
              - duration
            properties:
              title: 
                type: string
              artist:
                type: string
              duration:
                type: integer
              album:
                type: string
              genre:
                type: string
